# Generated by Django 4.2.6 on 2023-10-28 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_banco_estado_paqueteria_tarjeta_envio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarjeta',
            name='pedido',
        ),
    ]
